project:
  type: website
  title: "Technology Job Market: Salary Disparity Analysis"
  output-dir: _output
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!*.md"
    - "!README.md"
    - "!DEPLOYMENT_SUMMARY.md"
    - "!ML_LAB_SOLUTION.md"
    - "!PROJECT_STATUS.md"
    - "!SETUP.md"
    - "!salary-analysis.qmd"  # Exclude old monolithic file
  preview:
    port: 4200
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "Tech Career Intelligence: Data-Driven Job Market Guide"
  description: Your comprehensive guide to making informed career decisions with real market data
  
  navbar:
    title: "Career Intelligence"
    left:
      - href: index.qmd
        text: "Home"
      - text: "Salary Analysis"
        menu:
          - href: salary-overview.qmd
            text: "Overview & Summary"
          - href: salary-experience.qmd
            text: "Experience Levels"
          - href: salary-education.qmd
            text: "Education & Skills"
          - href: salary-industry.qmd
            text: "Industry Analysis"
          - href: salary-geographic.qmd
            text: "Geographic Trends"
          - href: salary-statistical.qmd
            text: "Statistical Analysis"
      - href: regional-trends.qmd
        text: "Regional Intelligence"
      - href: remote-work.qmd
        text: "Remote Work"
      - href: notebooks/job_market_skill_analysis.ipynb
        text: "Deep Analysis"
    right:
      - icon: github
        href: https://github.com/samarthya/ad688-scratch
        aria-label: GitHub

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Career Intelligence Hub"
        contents:
          - index.qmd
          - data-methodology.qmd
      - section: "Comprehensive Salary Analysis"
        contents:
          - salary-overview.qmd
          - salary-experience.qmd
          - salary-education.qmd
          - salary-industry.qmd
          - salary-geographic.qmd
          - salary-statistical.qmd
      - section: "Market Intelligence" 
        contents:
          - regional-trends.qmd
          - remote-work.qmd
      - section: "Technical Deep Dive"
        contents:
          - notebooks/job_market_skill_analysis.ipynb
          - data-analysis.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    highlight-style: github
    code-fold: true
    code-tools: true
    fig-width: 10
    fig-height: 6
    fig-dpi: 300
    
bibliography: references.bib
csl: csl/econometrica.csl
cite-method: citeproc

execute:
  freeze: auto
  cache: true
  warning: false
  message: false
  
python:
  type: conda
  environment: .venv