project:
  type: website
  title: Tech Career Intelligence
  output-dir: _salary
  render:
    - "*.qmd"
    - "!*.ipynb"
    - "!*.md"
    - "!README.md"
  preview:
    port: 4200
    watch-inputs: true
    navigate: true

website:
  title: Tech Career Intelligence
  navbar:
    title: Career Intelligence
    left:
      - href: index.qmd
        text: Home
      - href: data-pipeline.qmd
        text: Data Pipeline
      - href: salary-insights.qmd
        text: Salary Insights
      - href: predictive-analytics.qmd
        text: Predictive Analytics
      - href: market-dashboard.qmd
        text: Market Dashboard
      - href: tech-career-intelligence-report.qmd
        text: Full Report
    right:
      - icon: github
        href: https://github.com/samarthya/ad688-scratch
        aria-label: GitHub

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    embed-resources: true
    css: styles.css
    html-math-method: katex
  docx:
    toc: true
    toc-depth: 3
    number-sections: true
    highlight-style: github
    fig-width: 8
    fig-height: 6
    fig-dpi: 300

bibliography: references.bib
csl: csl/econometrica.csl
cite-method: citeproc

execute:
  cache: true
  warning: True
  message: false

python:
  type: venv
  environment: .venv
