project:
  type: website
  title: Tech Career Intelligence
  output-dir: _salary
  render:
    - "*.qmd"
    - "!*.ipynb"
    - "!*.md"
    - "!README.md"
  preview:
    port: 4200
    watch-inputs: true
    navigate: true

author:
  - name: Saurabh Sharma
    affiliations:
      - id: bu
        name: Boston Uninversity
        city: Boston
        state: MA
  - name: Haocun Wang
    affiliations:
      - id: ha
        name: Boston University
        city: Boston
        state: MA
# Haocun Wang
website:
  title: Tech Career Intelligence
  navbar:
    title: Career Intelligence
    left:
      - href: index.qmd
        text: Home
      - href: tech-career-intelligence-report.qmd
        text: Full Report
      - href: salary-insights.qmd
        text: Salary Insights
      - href: market-dashboard.qmd
        text: Market Dashboard
      - href: predictive-analytics.qmd
        text: Predictive Analytics
      - text: Technical Details
        menu:
          - href: methodology.qmd
            text: Methodology
          - href: data-pipeline.qmd
            text: Data Pipeline
    right:
      - icon: github
        href: https://github.com/samarthya/ad688-scratch
        aria-label: GitHub

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    embed-resources: true
    css: styles.css
    mathjax: false
    self-contained: true
  docx:
    toc: true
    toc-depth: 3
    number-sections: true
    highlight-style: github
    fig-width: 8
    fig-height: 6
    fig-dpi: 300
  pptx:
    fig-width: 10
    fig-height: 7.5
    fig-dpi: 300

bibliography: references.bib
csl: csl/econometrica.csl
cite-method: citeproc

execute:
  cache: true
  warning: True
  message: False

python:
  type: venv
  environment: .venv
