project:
  type: website
  title: "Technology Job Market: Salary Disparity Analysis"
  output-dir: _output
  preview:
    port: 4200
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "Salary Disparity Analysis: Technology Job Market"
  description: "Investigating compensation inequities in the technology industry"
  
  navbar:
    title: "Salary Disparity Research"
    left:
      - href: index.qmd
        text: Home
      - href: notebooks/job_market_skill_analysis.ipynb
        text: Interactive Analysis
      - href: salary-analysis.qmd
        text: Salary Research
      - href: data-analysis.qmd
        text: Data Processing
      - href: regional-trends.qmd
        text: Geographic Analysis
      - href: remote-work.qmd
        text: Remote Work Impact
    right:
      - icon: github
        href: https://github.com/samarthya/ad688-scratch
        aria-label: GitHub

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Research Overview"
        contents:
          - index.qmd
          - data-methodology.qmd
      - section: "Salary Disparity Analysis" 
        contents:
          - notebooks/job_market_skill_analysis.ipynb
          - salary-analysis.qmd
      - section: "Supporting Analysis"
        contents:
          - regional-trends.qmd
          - remote-work.qmd
          - data-analysis.qmd

format:
  html:
    theme: flatly
    css: 
      - styles.css
      - navigation.css
    toc: true
    toc-depth: 3
    number-sections: true
    highlight-style: github
    code-fold: true
    code-tools: true
    fig-width: 10
    fig-height: 6
    fig-dpi: 300
    
bibliography: references.bib
csl: csl/econometrica.csl
cite-method: citeproc

execute:
  freeze: auto
  cache: true
  warning: false
  message: false